schema = 3

[mod]
  [mod."github.com/gofrs/uuid/v5"]
    version = "v5.4.0"
    hash = "sha256-RbSw7vig1/d+qEe8q7pJ99l2dbQ95YnaJbnJkR+2BL0="
  [mod."github.com/google/uuid"]
    version = "v1.6.0"
    hash = "sha256-VWl9sqUzdOuhW0KzQlv0gwwUQClYkmZwSydHG2sALYw="
  [mod."github.com/jackc/pgpassfile"]
    version = "v1.0.0"
    hash = "sha256-H0nFbC34/3pZUFnuiQk9W7yvAMh6qJDrqvHp+akBPLM="
  [mod."github.com/jackc/pgservicefile"]
    version = "v0.0.0-20240606120523-5a60cdf6a761"
    hash = "sha256-ETpGsLAA2wcm5xJBayr/mZrCE1YsWbnkbSSX3ptrFn0="
  [mod."github.com/jackc/pgx/v5"]
    version = "v5.8.0"
    hash = "sha256-Mq5/A/Obcceu6kKxUv30DPC2ZaVvD8Iq/YtmLm1BVec="
  [mod."github.com/jackc/puddle/v2"]
    version = "v2.2.2"
    hash = "sha256-IUxdu4JYfsCh/qlz2SiUWu7EVPHhyooiVA4oaS2Z6yk="
  [mod."golang.org/x/sync"]
    version = "v0.17.0"
    hash = "sha256-M85lz4hK3/fzmcUViAp/CowHSxnr3BHSO7pjHp1O6i0="
  [mod."golang.org/x/text"]
    version = "v0.29.0"
    hash = "sha256-2cWBtJje+Yc+AnSgCANqBlIwnOMZEGkpQ2cFI45VfLI="
